#!/bin/sh

mkdir supplemental_data_s12
cd supplemental_data_s12

ln -s ../../../../../_m/latent_variables.csv

for ii in ../../../../_m/module*
do
   ln -s $ii 
done


for ii in ../../../_m/module*.pdf
do
   ln -s $ii 
done

cd -

tar cfzhv supplemental_data_s12.tar.gz supplemental_data_s12
