#!/bin/bash

EQTLS="../../_m"
DRD2="../../drd2_ids/_m"

for feature in genes trasncripts exons junctions; do
    if [ $feature = genes ]; then
    ## Use caudate cis-eQTL, FDR <= 0.01 as cutoff for GTEx
	grep -f $DRD2/DRD2_${feature}.txt $EQTLS/cis_eqtls_${feature}.ctxt > cis_eqtls_${feature}.ctxt
    elif [ $feature = trasncripts ]; then
	## Use caudate cis-eQTL, FDR <= 0.01 as cutoff for GTEx
	grep -f $DRD2/DRD2_transcripts.txt $EQTLS/cis_eqtl_${feature}.ctxt > cis_eqtl_${feature}.ctxt ## Extract only DRD2 related features
    else
    ## Use caudate cis-eQTL, FDR <= 0.01 as cutoff for GTEx
	grep -f $DRD2/DRD2_${feature}.txt $EQTLS/cis_eqtl_${feature}.ctxt > cis_eqtl_${feature}.ctxt ## Extract only DRD2 related features
    fi
done
