#!/bin/bash

SIZE=600

ln -s . ./output

seq 0 $SIZE 354000 | \
    parallel --jobs 30 "bash ../_h/parallel_compute_weights.sh --batch_number {} --batch_size $SIZE --threads 1 2> cw_{}_error.out 1> cw_{}_summary.out"

bash ../_h/generate_summary_stats.sh 2> Phase3_Caudate.err 1> Phase3_Caudate.profile
python ../_h/gen_positions.py 
